import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "./src/components/shared/Footer";
import Header from "./src/components/shared/Header";
import { Theme } from '@radix-ui/themes';
import '@radix-ui/themes/styles.css';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hospital",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme>
          {/* <header>
            <SignedOut>
              <SignInButton />
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
          </header> */}
          <header>
            <Header />
          </header>
          {children}
          <div>
            <Footer />
          </div>
        </Theme>
      </body>
    </html>
  );
}
